<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\MongoDBException;
use Pagerfanta\Adapter\DoctrineODMMongoDBAdapter;
use Pagerfanta\Pagerfanta;


/**
 * PeopleRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class PeopleRepository extends DocumentRepository
{
    public function findMatchPaging($data, $page = 1)
    {
        $qb = $this->createQueryBuilder();
        if($data['name']) {
            $qb = $qb->field('name')->equals($data['name']);
        }

        if($data['function'] != '不限') {
            $qb = $qb->field('function')->equals($data['function']);
        }

        if($data['education1'] != '不限') {
            $qb = $qb->field('education1')->equals($data['education1']);
        }

        if($data['status1'] != '不限') {
            $qb = $qb->field('status1')->equals($data['status1']);
        }

        if($data['sex'] != '不限') {
            $qb = $qb->field('sex')->equals($data['sex']);
        }

        if($data['employ_type'] != '不限') {
            $qb = $qb->field('employ_type')->equals($data['employ_type']);
        }

        if($data['workYear']) {
            $qb = $qb->field('workYear')->equals($data['workYear']);
        }

        if($data['availability'] != '不限') {
            $qb = $qb->field('availability')->equals($data['availability']);
        }

        return $this->createPaginator($qb, $page);
    }

    public function findAllPaging($page)
    {
        $qb = $this->createQueryBuilder();

        return $this->createPaginator($qb, $page);
    }

    private function createPaginator($qb, $page)
    {
        $paginator = new Pagerfanta(new DoctrineODMMongoDBAdapter($qb));
        $paginator->setMaxPerPage(10);
        $paginator->setCurrentPage($page);

        return $paginator;

    }
}
