<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Doctrine\ODM\MongoDB\MongoDBException;

/**
 * PeopleRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class PeopleRepository extends DocumentRepository
{
    public function searchData($data)
    {
        $qb = $this->createQueryBuilder();
        if($data['name']) {
            $qb = field('name')->equals($data['name']);
        }
        if($data['marriage'] != '不限') {
            $qb = field('marriage')->equals($data['marriage']);
        }
        return $qb->getQuery()->execute();
    }


}
